name: Deploy Backend

on:
  push:
    branches: [ backend ]  # backend 브랜치에 push 발생 시

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user
            chmod +x ./deploy.sh
            ./deploy.sh
