name: Deploy Backend

on:
  push:
    branches: [ backend ]  # backend 브랜치에 push 발생 시

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/kpsa-hackathon-2025-team08 || exit

            echo ">> Pulling latest code"
            git pull origin backend

            echo ">> Building Docker image"
            docker build -t memory-garden backend/

            echo ">> Restarting container"
            docker rm -f $(docker ps -aq) || true
            docker run -d -p 80:8080 --name memory-garden-container memory-garden
